-- Placement V2 — validation lineage (PlacementDecisionValidation + PointAcquisitionValidationRef).
-- Contract: docs/learning-v2/DATA_MODEL_V2_PRISMA_CHANGE_PLAN.md §10, §15a. ADDITIVE ONLY (2 enums + 2 tables).
-- Body generated by `prisma migrate diff`; custom XOR/pairing CHECKs + per-target partial uniques appended.

-- CreateEnum
CREATE TYPE "PlacementValidationKind" AS ENUM ('EVIDENCE_BACKED', 'POLICY_PREREQ');

-- CreateEnum
CREATE TYPE "PlacementValidationTargetKind" AS ENUM ('EXPECTATION_REVISION', 'ROADMAP_POINT');

-- CreateTable
CREATE TABLE "placement_decision_validation" (
    "id" UUID NOT NULL,
    "placement_decision_id" UUID NOT NULL,
    "target_kind" "PlacementValidationTargetKind" NOT NULL,
    "skill_level_expectation_revision_id" UUID,
    "roadmap_point_id" UUID,
    "roadmap_point_revision_id" UUID,
    "validation_kind" "PlacementValidationKind" NOT NULL,
    "policy_version" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "placement_decision_validation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "point_acquisition_validation_ref" (
    "id" UUID NOT NULL,
    "point_acquisition_event_id" UUID NOT NULL,
    "placement_decision_validation_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "point_acquisition_validation_ref_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "placement_decision_validation_placement_decision_id_idx" ON "placement_decision_validation"("placement_decision_id");

-- CreateIndex
CREATE INDEX "point_acquisition_validation_ref_placement_decision_validat_idx" ON "point_acquisition_validation_ref"("placement_decision_validation_id");

-- CreateIndex
CREATE INDEX "point_acquisition_validation_ref_point_acquisition_event_id_idx" ON "point_acquisition_validation_ref"("point_acquisition_event_id");

-- CreateIndex
CREATE UNIQUE INDEX "point_acquisition_validation_ref_point_acquisition_event_id_key" ON "point_acquisition_validation_ref"("point_acquisition_event_id", "placement_decision_validation_id");

-- AddForeignKey
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "placement_decision_validation_placement_decision_id_fkey" FOREIGN KEY ("placement_decision_id") REFERENCES "placement_decision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "placement_decision_validation_skill_level_expectation_revi_fkey" FOREIGN KEY ("skill_level_expectation_revision_id") REFERENCES "skill_level_expectation_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "placement_decision_validation_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "placement_decision_validation_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_validation_ref" ADD CONSTRAINT "point_acquisition_validation_ref_point_acquisition_event_i_fkey" FOREIGN KEY ("point_acquisition_event_id") REFERENCES "point_acquisition_event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_validation_ref" ADD CONSTRAINT "point_acquisition_validation_ref_placement_decision_valida_fkey" FOREIGN KEY ("placement_decision_validation_id") REFERENCES "placement_decision_validation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ============================================================================
-- Custom PostgreSQL constraints (Prisma cannot express) — Placement V2 lineage
-- ============================================================================

-- Exactly one typed target per validation row (expectation revision XOR roadmap point).
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "chk_placement_validation_target_xor" CHECK ((("skill_level_expectation_revision_id" IS NOT NULL)::int + ("roadmap_point_id" IS NOT NULL)::int) = 1);
-- A point-target validation always pins its exact revision (correction 3).
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "chk_pdv_point_revision_paired" CHECK (("roadmap_point_revision_id" IS NOT NULL) = ("roadmap_point_id" IS NOT NULL));
-- Non-empty policy version (load-bearing).
ALTER TABLE "placement_decision_validation" ADD CONSTRAINT "chk_pdv_policy_version_nonempty" CHECK (length(trim("policy_version")) > 0);
-- Dedup per (decision, target).
CREATE UNIQUE INDEX "uq_pdv_point" ON "placement_decision_validation" ("placement_decision_id", "roadmap_point_id") WHERE "roadmap_point_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_pdv_expectation" ON "placement_decision_validation" ("placement_decision_id", "skill_level_expectation_revision_id") WHERE "skill_level_expectation_revision_id" IS NOT NULL;
