-- V2 Data Model — Waves B/C/D (roadmap-point graph, teaching blueprint, mastery requirement,
-- learner-fact evidence lineage, and derived roadmap generation/projection).
-- Contract: docs/learning-v2/DATA_MODEL_V2_PRISMA_CHANGE_PLAN.md §7–§16, §22.
-- ADDITIVE ONLY: new enums + new tables + additive nullable columns on skill_measurement / activity_attempt.
-- No DROP, no destructive ALTER, no data backfill. Body generated by `prisma migrate diff`;
-- custom PostgreSQL CHECK / partial-unique constraints appended below.

-- CreateEnum
CREATE TYPE "BlueprintBindingRole" AS ENUM ('TEACH', 'PRACTICE', 'EVIDENCE', 'EXPOSURE');

-- CreateEnum
CREATE TYPE "PointAcquisitionType" AS ENUM ('LEARNED', 'VALIDATED');

-- CreateEnum
CREATE TYPE "TeachingSessionStatus" AS ENUM ('NOT_STARTED', 'TEACHING', 'PRACTICING', 'REMEDIATING', 'MASTERY_CHECK', 'COMPLETED', 'ABANDONED');

-- CreateEnum
CREATE TYPE "MasteryEvaluationOutcome" AS ENUM ('SATISFIED', 'NOT_SATISFIED', 'INSUFFICIENT_EVIDENCE');

-- CreateEnum
CREATE TYPE "RoadmapGenerationStatus" AS ENUM ('CURRENT', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "RoadmapAvailabilityState" AS ENUM ('LOCKED', 'AVAILABLE', 'IN_PROGRESS', 'CONTENT_UNAVAILABLE');

-- CreateEnum
CREATE TYPE "RoadmapAttentionState" AS ENUM ('NONE', 'REVIEW_DUE', 'REPAIR_REQUIRED');

-- AlterEnum
ALTER TYPE "SkillMeasurementSource" ADD VALUE 'TEACHING_MASTERY';

-- AlterTable
ALTER TABLE "activity_attempt" ADD COLUMN     "teaching_session_id" UUID;

-- AlterTable
ALTER TABLE "skill_measurement" ADD COLUMN     "ai_evaluation_id" UUID,
ADD COLUMN     "detail_meta" JSONB,
ADD COLUMN     "evidence_kind" TEXT,
ADD COLUMN     "independence_level" SMALLINT,
ADD COLUMN     "skill_level_expectation_revision_id" UUID,
ADD COLUMN     "task_content_revision_id" UUID,
ADD COLUMN     "teaching_session_id" UUID;

-- CreateTable
CREATE TABLE "roadmap_point" (
    "id" UUID NOT NULL,
    "point_key" TEXT NOT NULL,
    "level_id" UUID NOT NULL,
    "status" "ContainerStatus" NOT NULL DEFAULT 'DRAFT',
    "published_revision_id" UUID,
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "roadmap_point_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roadmap_point_revision" (
    "id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "status" "RevisionStatus" NOT NULL DEFAULT 'DRAFT',
    "title" TEXT NOT NULL,
    "learning_outcome" JSONB,
    "topic_id" UUID,
    "sort_order_default" INTEGER NOT NULL,
    "required_flag" BOOLEAN NOT NULL DEFAULT true,
    "estimated_effort_min" INTEGER,
    "reviewed_by" UUID,
    "published_by" UUID,
    "published_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "roadmap_point_revision_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roadmap_point_prerequisite" (
    "id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "prerequisite_point_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roadmap_point_prerequisite_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roadmap_point_skill_expectation" (
    "id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "skill_level_expectation_id" UUID NOT NULL,
    "role" "SkillContributionRole" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roadmap_point_skill_expectation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_blueprint" (
    "id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "status" "ContainerStatus" NOT NULL DEFAULT 'DRAFT',
    "published_revision_id" UUID,
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "teaching_blueprint_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_blueprint_revision" (
    "id" UUID NOT NULL,
    "blueprint_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "status" "RevisionStatus" NOT NULL DEFAULT 'DRAFT',
    "estimated_duration_min" INTEGER,
    "reviewed_by" UUID,
    "published_by" UUID,
    "published_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "teaching_blueprint_revision_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_blueprint_stage" (
    "id" UUID NOT NULL,
    "blueprint_revision_id" UUID NOT NULL,
    "stage_key" TEXT,
    "position" INTEGER NOT NULL,
    "stage_type" TEXT NOT NULL,
    "branch_from_stage_id" UUID,
    "config" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teaching_blueprint_stage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_blueprint_content_binding" (
    "id" UUID NOT NULL,
    "blueprint_stage_id" UUID NOT NULL,
    "lesson_revision_id" UUID,
    "activity_id" UUID,
    "media_asset_id" UUID,
    "role" "BlueprintBindingRole" NOT NULL,
    "position" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teaching_blueprint_content_binding_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mastery_requirement" (
    "id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "status" "ContainerStatus" NOT NULL DEFAULT 'DRAFT',
    "current_revision_id" UUID,
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mastery_requirement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mastery_requirement_revision" (
    "id" UUID NOT NULL,
    "requirement_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "status" "RevisionStatus" NOT NULL DEFAULT 'DRAFT',
    "gates" JSONB NOT NULL,
    "policy_version" TEXT NOT NULL,
    "reviewed_by" UUID,
    "published_by" UUID,
    "published_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mastery_requirement_revision_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mastery_requirement_skill_expectation" (
    "id" UUID NOT NULL,
    "requirement_revision_id" UUID NOT NULL,
    "skill_level_expectation_revision_id" UUID NOT NULL,
    "role" "SkillContributionRole" NOT NULL,
    "required_evidence_kinds" JSONB NOT NULL,
    "min_independence" SMALLINT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mastery_requirement_skill_expectation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "placement_decision" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "subject_id" UUID NOT NULL,
    "track_id" UUID,
    "source_assessment_attempt_id" UUID,
    "policy_version" TEXT NOT NULL,
    "recommended_study_level_id" UUID,
    "supersedes_decision_id" UUID,
    "client_request_id" TEXT,
    "snapshot" JSONB NOT NULL,
    "decided_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "placement_decision_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_session" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "blueprint_revision_id" UUID NOT NULL,
    "roadmap_generation_id" UUID,
    "status" "TeachingSessionStatus" NOT NULL DEFAULT 'NOT_STARTED',
    "current_step" JSONB,
    "started_at" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "teaching_session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teaching_session_content_pin" (
    "id" UUID NOT NULL,
    "teaching_session_id" UUID NOT NULL,
    "lesson_revision_id" UUID,
    "activity_id" UUID,
    "media_asset_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teaching_session_content_pin_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_measurement_evidence_ref" (
    "id" UUID NOT NULL,
    "skill_measurement_id" UUID NOT NULL,
    "assessment_response_id" UUID,
    "activity_attempt_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "skill_measurement_evidence_ref_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mastery_evaluation" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "mastery_requirement_revision_id" UUID NOT NULL,
    "outcome" "MasteryEvaluationOutcome" NOT NULL,
    "policy_version" TEXT NOT NULL,
    "evidence_cutoff_at" TIMESTAMP(3) NOT NULL,
    "evidence_boundary_key" TEXT,
    "gate_summary" JSONB NOT NULL,
    "evaluated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mastery_evaluation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mastery_evaluation_evidence" (
    "id" UUID NOT NULL,
    "mastery_evaluation_id" UUID NOT NULL,
    "skill_measurement_id" UUID NOT NULL,
    "evidence_role" SMALLINT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mastery_evaluation_evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "point_acquisition_event" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "acquisition_type" "PointAcquisitionType" NOT NULL,
    "mastery_evaluation_id" UUID,
    "placement_decision_id" UUID,
    "validation_application_policy_version" TEXT,
    "policy_version" TEXT,
    "acquired_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "point_acquisition_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "learner_roadmap_generation" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "subject_id" UUID NOT NULL,
    "track_id" UUID NOT NULL,
    "generation_no" INTEGER NOT NULL,
    "engine_version" TEXT NOT NULL,
    "source_placement_decision_id" UUID,
    "status" "RoadmapGenerationStatus" NOT NULL DEFAULT 'CURRENT',
    "supersedes_generation_id" UUID,
    "generated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "learner_roadmap_generation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "roadmap_point_projection" (
    "id" UUID NOT NULL,
    "roadmap_generation_id" UUID NOT NULL,
    "roadmap_point_id" UUID NOT NULL,
    "roadmap_point_revision_id" UUID NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "acquisition" "PointAcquisitionType",
    "availability" "RoadmapAvailabilityState" NOT NULL DEFAULT 'LOCKED',
    "attention" "RoadmapAttentionState" NOT NULL DEFAULT 'NONE',
    "derived_meta" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "roadmap_point_projection_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_point_key_key" ON "roadmap_point"("point_key");

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_published_revision_id_key" ON "roadmap_point"("published_revision_id");

-- CreateIndex
CREATE INDEX "roadmap_point_level_id_idx" ON "roadmap_point"("level_id");

-- CreateIndex
CREATE INDEX "roadmap_point_revision_roadmap_point_id_status_idx" ON "roadmap_point_revision"("roadmap_point_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_revision_roadmap_point_id_version_no_key" ON "roadmap_point_revision"("roadmap_point_id", "version_no");

-- CreateIndex
CREATE INDEX "roadmap_point_prerequisite_prerequisite_point_id_idx" ON "roadmap_point_prerequisite"("prerequisite_point_id");

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_prerequisite_roadmap_point_revision_id_prereq_key" ON "roadmap_point_prerequisite"("roadmap_point_revision_id", "prerequisite_point_id");

-- CreateIndex
CREATE INDEX "roadmap_point_skill_expectation_skill_level_expectation_id_idx" ON "roadmap_point_skill_expectation"("skill_level_expectation_id");

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_skill_expectation_roadmap_point_revision_id_s_key" ON "roadmap_point_skill_expectation"("roadmap_point_revision_id", "skill_level_expectation_id");

-- CreateIndex
CREATE UNIQUE INDEX "teaching_blueprint_roadmap_point_id_key" ON "teaching_blueprint"("roadmap_point_id");

-- CreateIndex
CREATE UNIQUE INDEX "teaching_blueprint_published_revision_id_key" ON "teaching_blueprint"("published_revision_id");

-- CreateIndex
CREATE UNIQUE INDEX "teaching_blueprint_revision_blueprint_id_version_no_key" ON "teaching_blueprint_revision"("blueprint_id", "version_no");

-- CreateIndex
CREATE INDEX "teaching_blueprint_stage_blueprint_revision_id_position_idx" ON "teaching_blueprint_stage"("blueprint_revision_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "teaching_blueprint_stage_blueprint_revision_id_position_key" ON "teaching_blueprint_stage"("blueprint_revision_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "teaching_blueprint_content_binding_blueprint_stage_id_posit_key" ON "teaching_blueprint_content_binding"("blueprint_stage_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_requirement_roadmap_point_id_key" ON "mastery_requirement"("roadmap_point_id");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_requirement_current_revision_id_key" ON "mastery_requirement"("current_revision_id");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_requirement_revision_requirement_id_version_no_key" ON "mastery_requirement_revision"("requirement_id", "version_no");

-- CreateIndex
CREATE INDEX "mastery_requirement_skill_expectation_skill_level_expectati_idx" ON "mastery_requirement_skill_expectation"("skill_level_expectation_revision_id");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_requirement_skill_expectation_requirement_revision__key" ON "mastery_requirement_skill_expectation"("requirement_revision_id", "skill_level_expectation_revision_id");

-- CreateIndex
CREATE INDEX "placement_decision_user_id_subject_id_decided_at_idx" ON "placement_decision"("user_id", "subject_id", "decided_at");

-- CreateIndex
CREATE INDEX "teaching_session_user_id_status_idx" ON "teaching_session"("user_id", "status");

-- CreateIndex
CREATE INDEX "teaching_session_user_id_roadmap_point_id_status_idx" ON "teaching_session"("user_id", "roadmap_point_id", "status");

-- CreateIndex
CREATE INDEX "teaching_session_content_pin_teaching_session_id_idx" ON "teaching_session_content_pin"("teaching_session_id");

-- CreateIndex
CREATE INDEX "skill_measurement_evidence_ref_assessment_response_id_idx" ON "skill_measurement_evidence_ref"("assessment_response_id");

-- CreateIndex
CREATE INDEX "skill_measurement_evidence_ref_activity_attempt_id_idx" ON "skill_measurement_evidence_ref"("activity_attempt_id");

-- CreateIndex
CREATE INDEX "skill_measurement_evidence_ref_skill_measurement_id_idx" ON "skill_measurement_evidence_ref"("skill_measurement_id");

-- CreateIndex
CREATE INDEX "mastery_evaluation_user_id_roadmap_point_id_evaluated_at_idx" ON "mastery_evaluation"("user_id", "roadmap_point_id", "evaluated_at");

-- CreateIndex
CREATE INDEX "mastery_evaluation_evidence_skill_measurement_id_idx" ON "mastery_evaluation_evidence"("skill_measurement_id");

-- CreateIndex
CREATE INDEX "mastery_evaluation_evidence_mastery_evaluation_id_idx" ON "mastery_evaluation_evidence"("mastery_evaluation_id");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_evaluation_evidence_mastery_evaluation_id_skill_mea_key" ON "mastery_evaluation_evidence"("mastery_evaluation_id", "skill_measurement_id");

-- CreateIndex
CREATE INDEX "point_acquisition_event_user_id_roadmap_point_id_acquired_a_idx" ON "point_acquisition_event"("user_id", "roadmap_point_id", "acquired_at");

-- CreateIndex
CREATE INDEX "learner_roadmap_generation_user_id_subject_id_status_idx" ON "learner_roadmap_generation"("user_id", "subject_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "learner_roadmap_generation_user_id_subject_id_generation_no_key" ON "learner_roadmap_generation"("user_id", "subject_id", "generation_no");

-- CreateIndex
CREATE INDEX "roadmap_point_projection_roadmap_generation_id_sort_order_idx" ON "roadmap_point_projection"("roadmap_generation_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "roadmap_point_projection_roadmap_generation_id_roadmap_poin_key" ON "roadmap_point_projection"("roadmap_generation_id", "roadmap_point_id");

-- CreateIndex
CREATE INDEX "activity_attempt_teaching_session_id_idx" ON "activity_attempt"("teaching_session_id");

-- CreateIndex
CREATE INDEX "skill_measurement_teaching_session_id_idx" ON "skill_measurement"("teaching_session_id");

-- AddForeignKey
ALTER TABLE "roadmap_point" ADD CONSTRAINT "roadmap_point_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "level"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point" ADD CONSTRAINT "roadmap_point_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point" ADD CONSTRAINT "roadmap_point_published_revision_id_fkey" FOREIGN KEY ("published_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_revision" ADD CONSTRAINT "roadmap_point_revision_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_revision" ADD CONSTRAINT "roadmap_point_revision_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "topic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_revision" ADD CONSTRAINT "roadmap_point_revision_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_revision" ADD CONSTRAINT "roadmap_point_revision_published_by_fkey" FOREIGN KEY ("published_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_prerequisite" ADD CONSTRAINT "roadmap_point_prerequisite_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_prerequisite" ADD CONSTRAINT "roadmap_point_prerequisite_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_prerequisite" ADD CONSTRAINT "roadmap_point_prerequisite_prerequisite_point_id_fkey" FOREIGN KEY ("prerequisite_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_skill_expectation" ADD CONSTRAINT "roadmap_point_skill_expectation_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_skill_expectation" ADD CONSTRAINT "roadmap_point_skill_expectation_skill_level_expectation_id_fkey" FOREIGN KEY ("skill_level_expectation_id") REFERENCES "skill_level_expectation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint" ADD CONSTRAINT "teaching_blueprint_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint" ADD CONSTRAINT "teaching_blueprint_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint" ADD CONSTRAINT "teaching_blueprint_published_revision_id_fkey" FOREIGN KEY ("published_revision_id") REFERENCES "teaching_blueprint_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_revision" ADD CONSTRAINT "teaching_blueprint_revision_blueprint_id_fkey" FOREIGN KEY ("blueprint_id") REFERENCES "teaching_blueprint"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_revision" ADD CONSTRAINT "teaching_blueprint_revision_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_revision" ADD CONSTRAINT "teaching_blueprint_revision_published_by_fkey" FOREIGN KEY ("published_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_stage" ADD CONSTRAINT "teaching_blueprint_stage_blueprint_revision_id_fkey" FOREIGN KEY ("blueprint_revision_id") REFERENCES "teaching_blueprint_revision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_stage" ADD CONSTRAINT "teaching_blueprint_stage_branch_from_stage_id_fkey" FOREIGN KEY ("branch_from_stage_id") REFERENCES "teaching_blueprint_stage"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_content_binding" ADD CONSTRAINT "teaching_blueprint_content_binding_blueprint_stage_id_fkey" FOREIGN KEY ("blueprint_stage_id") REFERENCES "teaching_blueprint_stage"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_content_binding" ADD CONSTRAINT "teaching_blueprint_content_binding_lesson_revision_id_fkey" FOREIGN KEY ("lesson_revision_id") REFERENCES "lesson_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_content_binding" ADD CONSTRAINT "teaching_blueprint_content_binding_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "activity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_blueprint_content_binding" ADD CONSTRAINT "teaching_blueprint_content_binding_media_asset_id_fkey" FOREIGN KEY ("media_asset_id") REFERENCES "media_asset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement" ADD CONSTRAINT "mastery_requirement_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement" ADD CONSTRAINT "mastery_requirement_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement" ADD CONSTRAINT "mastery_requirement_current_revision_id_fkey" FOREIGN KEY ("current_revision_id") REFERENCES "mastery_requirement_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement_revision" ADD CONSTRAINT "mastery_requirement_revision_requirement_id_fkey" FOREIGN KEY ("requirement_id") REFERENCES "mastery_requirement"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement_revision" ADD CONSTRAINT "mastery_requirement_revision_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement_revision" ADD CONSTRAINT "mastery_requirement_revision_published_by_fkey" FOREIGN KEY ("published_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement_skill_expectation" ADD CONSTRAINT "mastery_requirement_skill_expectation_requirement_revision_fkey" FOREIGN KEY ("requirement_revision_id") REFERENCES "mastery_requirement_revision"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_requirement_skill_expectation" ADD CONSTRAINT "mastery_requirement_skill_expectation_skill_level_expectat_fkey" FOREIGN KEY ("skill_level_expectation_revision_id") REFERENCES "skill_level_expectation_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement" ADD CONSTRAINT "skill_measurement_teaching_session_id_fkey" FOREIGN KEY ("teaching_session_id") REFERENCES "teaching_session"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement" ADD CONSTRAINT "skill_measurement_skill_level_expectation_revision_id_fkey" FOREIGN KEY ("skill_level_expectation_revision_id") REFERENCES "skill_level_expectation_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement" ADD CONSTRAINT "skill_measurement_ai_evaluation_id_fkey" FOREIGN KEY ("ai_evaluation_id") REFERENCES "ai_evaluation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement" ADD CONSTRAINT "skill_measurement_task_content_revision_id_fkey" FOREIGN KEY ("task_content_revision_id") REFERENCES "lesson_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "activity_attempt" ADD CONSTRAINT "activity_attempt_teaching_session_id_fkey" FOREIGN KEY ("teaching_session_id") REFERENCES "teaching_session"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "track"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_source_assessment_attempt_id_fkey" FOREIGN KEY ("source_assessment_attempt_id") REFERENCES "assessment_attempt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_recommended_study_level_id_fkey" FOREIGN KEY ("recommended_study_level_id") REFERENCES "level"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_decision" ADD CONSTRAINT "placement_decision_supersedes_decision_id_fkey" FOREIGN KEY ("supersedes_decision_id") REFERENCES "placement_decision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session" ADD CONSTRAINT "teaching_session_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session" ADD CONSTRAINT "teaching_session_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session" ADD CONSTRAINT "teaching_session_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session" ADD CONSTRAINT "teaching_session_blueprint_revision_id_fkey" FOREIGN KEY ("blueprint_revision_id") REFERENCES "teaching_blueprint_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session" ADD CONSTRAINT "teaching_session_roadmap_generation_id_fkey" FOREIGN KEY ("roadmap_generation_id") REFERENCES "learner_roadmap_generation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session_content_pin" ADD CONSTRAINT "teaching_session_content_pin_teaching_session_id_fkey" FOREIGN KEY ("teaching_session_id") REFERENCES "teaching_session"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session_content_pin" ADD CONSTRAINT "teaching_session_content_pin_lesson_revision_id_fkey" FOREIGN KEY ("lesson_revision_id") REFERENCES "lesson_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session_content_pin" ADD CONSTRAINT "teaching_session_content_pin_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "activity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teaching_session_content_pin" ADD CONSTRAINT "teaching_session_content_pin_media_asset_id_fkey" FOREIGN KEY ("media_asset_id") REFERENCES "media_asset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement_evidence_ref" ADD CONSTRAINT "skill_measurement_evidence_ref_skill_measurement_id_fkey" FOREIGN KEY ("skill_measurement_id") REFERENCES "skill_measurement"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement_evidence_ref" ADD CONSTRAINT "skill_measurement_evidence_ref_assessment_response_id_fkey" FOREIGN KEY ("assessment_response_id") REFERENCES "assessment_response"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_measurement_evidence_ref" ADD CONSTRAINT "skill_measurement_evidence_ref_activity_attempt_id_fkey" FOREIGN KEY ("activity_attempt_id") REFERENCES "activity_attempt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation" ADD CONSTRAINT "mastery_evaluation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation" ADD CONSTRAINT "mastery_evaluation_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation" ADD CONSTRAINT "mastery_evaluation_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation" ADD CONSTRAINT "mastery_evaluation_mastery_requirement_revision_id_fkey" FOREIGN KEY ("mastery_requirement_revision_id") REFERENCES "mastery_requirement_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation_evidence" ADD CONSTRAINT "mastery_evaluation_evidence_mastery_evaluation_id_fkey" FOREIGN KEY ("mastery_evaluation_id") REFERENCES "mastery_evaluation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mastery_evaluation_evidence" ADD CONSTRAINT "mastery_evaluation_evidence_skill_measurement_id_fkey" FOREIGN KEY ("skill_measurement_id") REFERENCES "skill_measurement"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "point_acquisition_event_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "point_acquisition_event_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "point_acquisition_event_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "point_acquisition_event_mastery_evaluation_id_fkey" FOREIGN KEY ("mastery_evaluation_id") REFERENCES "mastery_evaluation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "point_acquisition_event_placement_decision_id_fkey" FOREIGN KEY ("placement_decision_id") REFERENCES "placement_decision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "learner_roadmap_generation_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "learner_roadmap_generation_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "learner_roadmap_generation_track_id_fkey" FOREIGN KEY ("track_id") REFERENCES "track"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "learner_roadmap_generation_source_placement_decision_id_fkey" FOREIGN KEY ("source_placement_decision_id") REFERENCES "placement_decision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "learner_roadmap_generation_supersedes_generation_id_fkey" FOREIGN KEY ("supersedes_generation_id") REFERENCES "learner_roadmap_generation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_projection" ADD CONSTRAINT "roadmap_point_projection_roadmap_generation_id_fkey" FOREIGN KEY ("roadmap_generation_id") REFERENCES "learner_roadmap_generation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_projection" ADD CONSTRAINT "roadmap_point_projection_roadmap_point_id_fkey" FOREIGN KEY ("roadmap_point_id") REFERENCES "roadmap_point"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "roadmap_point_projection" ADD CONSTRAINT "roadmap_point_projection_roadmap_point_revision_id_fkey" FOREIGN KEY ("roadmap_point_revision_id") REFERENCES "roadmap_point_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ============================================================================
-- Custom PostgreSQL constraints (Prisma cannot express) — Waves B/C/D
-- Naming/pattern mirrors prisma/migrations/_custom_constraints.reference.sql.
-- ============================================================================

-- ---- Wave B (canonical graph) ----
ALTER TABLE "roadmap_point_prerequisite" ADD CONSTRAINT "chk_roadmap_point_prereq_no_self" CHECK ("roadmap_point_id" <> "prerequisite_point_id");
ALTER TABLE "teaching_blueprint_stage" ADD CONSTRAINT "chk_blueprint_stage_no_self_branch" CHECK ("branch_from_stage_id" IS NULL OR "branch_from_stage_id" <> "id");
ALTER TABLE "teaching_blueprint_content_binding" ADD CONSTRAINT "chk_blueprint_binding_content_xor" CHECK ((("lesson_revision_id" IS NOT NULL)::int + ("activity_id" IS NOT NULL)::int + ("media_asset_id" IS NOT NULL)::int) = 1);
ALTER TABLE "mastery_requirement_revision" ADD CONSTRAINT "chk_mastery_req_rev_policy_version_nonempty" CHECK (length(trim("policy_version")) > 0);
ALTER TABLE "mastery_requirement_skill_expectation" ADD CONSTRAINT "chk_mrse_min_independence_nonneg" CHECK ("min_independence" IS NULL OR "min_independence" >= 0);

-- ---- Wave C (learner facts + evidence lineage) ----
-- SkillMeasurement V2 additive
ALTER TABLE "skill_measurement" ADD CONSTRAINT "chk_sm_independence_level_nonneg" CHECK ("independence_level" IS NULL OR "independence_level" >= 0);
CREATE UNIQUE INDEX "uq_skill_measurement_teaching_idempotency" ON "skill_measurement" ("teaching_session_id", "skill_id", "source", "derivation_version") WHERE "teaching_session_id" IS NOT NULL;
-- SkillMeasurementEvidenceRef — XOR source, dedup per (measurement, source) NOT global
ALTER TABLE "skill_measurement_evidence_ref" ADD CONSTRAINT "chk_smer_source_xor" CHECK ((("assessment_response_id" IS NOT NULL)::int + ("activity_attempt_id" IS NOT NULL)::int) = 1);
CREATE UNIQUE INDEX "uq_smer_response" ON "skill_measurement_evidence_ref" ("skill_measurement_id", "assessment_response_id") WHERE "assessment_response_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_smer_attempt" ON "skill_measurement_evidence_ref" ("skill_measurement_id", "activity_attempt_id") WHERE "activity_attempt_id" IS NOT NULL;
-- TeachingSessionContentPin — XOR content, dedup per (session, object)
ALTER TABLE "teaching_session_content_pin" ADD CONSTRAINT "chk_teaching_session_pin_xor" CHECK ((("lesson_revision_id" IS NOT NULL)::int + ("activity_id" IS NOT NULL)::int + ("media_asset_id" IS NOT NULL)::int) = 1);
CREATE UNIQUE INDEX "uq_tscp_lesson_revision" ON "teaching_session_content_pin" ("teaching_session_id", "lesson_revision_id") WHERE "lesson_revision_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_tscp_activity" ON "teaching_session_content_pin" ("teaching_session_id", "activity_id") WHERE "activity_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_tscp_media" ON "teaching_session_content_pin" ("teaching_session_id", "media_asset_id") WHERE "media_asset_id" IS NOT NULL;
-- TeachingSession — one resumable (non-terminal) session per (user, point)
CREATE UNIQUE INDEX "uq_teaching_session_nonterminal" ON "teaching_session" ("user_id", "roadmap_point_id") WHERE "status" NOT IN ('COMPLETED', 'ABANDONED');
-- PlacementDecision — idempotency
ALTER TABLE "placement_decision" ADD CONSTRAINT "chk_placement_decision_policy_version_nonempty" CHECK (length(trim("policy_version")) > 0);
CREATE UNIQUE INDEX "uq_placement_decision_attempt_policy" ON "placement_decision" ("source_assessment_attempt_id", "policy_version") WHERE "source_assessment_attempt_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_placement_decision_client_request" ON "placement_decision" ("user_id", "client_request_id") WHERE "client_request_id" IS NOT NULL;
-- MasteryEvaluation — idempotency (all key cols NOT NULL → plain unique)
ALTER TABLE "mastery_evaluation" ADD CONSTRAINT "chk_me_policy_version_nonempty" CHECK (length(trim("policy_version")) > 0);
CREATE UNIQUE INDEX "uq_mastery_evaluation_idem" ON "mastery_evaluation" ("user_id", "roadmap_point_id", "mastery_requirement_revision_id", "evidence_cutoff_at");
-- PointAcquisitionEvent — provenance XOR + cause-based idempotency
ALTER TABLE "point_acquisition_event" ADD CONSTRAINT "chk_pae_provenance" CHECK (
  ("acquisition_type" = 'LEARNED' AND "mastery_evaluation_id" IS NOT NULL AND "placement_decision_id" IS NULL)
  OR
  ("acquisition_type" = 'VALIDATED' AND "placement_decision_id" IS NOT NULL AND "mastery_evaluation_id" IS NULL)
);
CREATE UNIQUE INDEX "uq_pae_learned" ON "point_acquisition_event" ("user_id", "roadmap_point_id", "mastery_evaluation_id") WHERE "mastery_evaluation_id" IS NOT NULL;
CREATE UNIQUE INDEX "uq_pae_validated" ON "point_acquisition_event" ("user_id", "roadmap_point_id", "placement_decision_id") WHERE "placement_decision_id" IS NOT NULL;

-- ---- Wave D (derived projections) ----
ALTER TABLE "learner_roadmap_generation" ADD CONSTRAINT "chk_gen_engine_version_nonempty" CHECK (length(trim("engine_version")) > 0);
CREATE UNIQUE INDEX "uq_roadmap_generation_current" ON "learner_roadmap_generation" ("user_id", "subject_id") WHERE "status" = 'CURRENT';
