-- V2 Data Model — Wave A (canonical skill/progression foundation).
-- Contract: docs/learning-v2/DATA_MODEL_V2_PRISMA_CHANGE_PLAN.md §5, §6, §22, §26.
-- ADDITIVE ONLY: one new enum + three new tables + one nullable column on "skill".
-- No DROP, no destructive ALTER, no data backfill/UPDATE; existing V1 rows remain valid.
-- Body generated by `prisma migrate diff --from-config-datasource --to-schema prisma/schema --script`;
-- custom PostgreSQL CHECK constraints (Prisma cannot express) appended below.

-- CreateEnum
CREATE TYPE "SkillContributionRole" AS ENUM ('REQUIRED', 'SUPPORTING', 'OPTIONAL');

-- AlterTable
ALTER TABLE "skill" ADD COLUMN     "primary_domain_id" UUID;

-- CreateTable
CREATE TABLE "subject_domain" (
    "id" UUID NOT NULL,
    "subject_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "status" "SkillStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_by" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "subject_domain_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_level_expectation" (
    "id" UUID NOT NULL,
    "skill_id" UUID NOT NULL,
    "level_id" UUID NOT NULL,
    "current_revision_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "skill_level_expectation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "skill_level_expectation_revision" (
    "id" UUID NOT NULL,
    "expectation_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "status" "RevisionStatus" NOT NULL DEFAULT 'DRAFT',
    "is_introduced" BOOLEAN NOT NULL DEFAULT false,
    "is_expected" BOOLEAN NOT NULL DEFAULT false,
    "is_reinforced" BOOLEAN NOT NULL DEFAULT false,
    "is_assessed" BOOLEAN NOT NULL DEFAULT false,
    "is_required_for_exit" BOOLEAN NOT NULL DEFAULT false,
    "required_evidence_kinds" JSONB NOT NULL,
    "min_independence" SMALLINT,
    "criticality" SMALLINT NOT NULL DEFAULT 0,
    "descriptor" JSONB,
    "reviewed_by" UUID,
    "published_by" UUID,
    "published_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "skill_level_expectation_revision_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "subject_domain_subject_id_idx" ON "subject_domain"("subject_id");

-- CreateIndex
CREATE UNIQUE INDEX "subject_domain_subject_id_code_key" ON "subject_domain"("subject_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "skill_level_expectation_current_revision_id_key" ON "skill_level_expectation"("current_revision_id");

-- CreateIndex
CREATE INDEX "skill_level_expectation_skill_id_idx" ON "skill_level_expectation"("skill_id");

-- CreateIndex
CREATE INDEX "skill_level_expectation_level_id_idx" ON "skill_level_expectation"("level_id");

-- CreateIndex
CREATE UNIQUE INDEX "skill_level_expectation_skill_id_level_id_key" ON "skill_level_expectation"("skill_id", "level_id");

-- CreateIndex
CREATE UNIQUE INDEX "skill_level_expectation_revision_expectation_id_version_no_key" ON "skill_level_expectation_revision"("expectation_id", "version_no");

-- AddForeignKey
ALTER TABLE "skill" ADD CONSTRAINT "skill_primary_domain_id_fkey" FOREIGN KEY ("primary_domain_id") REFERENCES "subject_domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_domain" ADD CONSTRAINT "subject_domain_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_domain" ADD CONSTRAINT "subject_domain_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "app_user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation" ADD CONSTRAINT "skill_level_expectation_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skill"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation" ADD CONSTRAINT "skill_level_expectation_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "level"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation" ADD CONSTRAINT "skill_level_expectation_current_revision_id_fkey" FOREIGN KEY ("current_revision_id") REFERENCES "skill_level_expectation_revision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation_revision" ADD CONSTRAINT "skill_level_expectation_revision_expectation_id_fkey" FOREIGN KEY ("expectation_id") REFERENCES "skill_level_expectation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation_revision" ADD CONSTRAINT "skill_level_expectation_revision_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "skill_level_expectation_revision" ADD CONSTRAINT "skill_level_expectation_revision_published_by_fkey" FOREIGN KEY ("published_by") REFERENCES "app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- ============================================================================
-- Custom PostgreSQL constraints (Prisma cannot express) — Wave A
-- Naming/pattern mirrors prisma/migrations/_custom_constraints.reference.sql.
-- Scope: only the load-bearing Wave-A CHECKs listed in DATA_MODEL_V2_PRISMA_CHANGE_PLAN §22/§26.
-- ============================================================================

-- Non-empty stable identifier (load-bearing — participates in unique(subject_id, code)).
ALTER TABLE "subject_domain" ADD CONSTRAINT "chk_subject_domain_code_nonempty" CHECK (length(trim("code")) > 0);

-- Independence / criticality are non-negative ordinals. Upper bound intentionally DEFERRED
-- (plan §22 leaves the ceiling "N" open); only the lower bound is enforced now.
ALTER TABLE "skill_level_expectation_revision" ADD CONSTRAINT "chk_sler_min_independence_nonneg" CHECK ("min_independence" IS NULL OR "min_independence" >= 0);
ALTER TABLE "skill_level_expectation_revision" ADD CONSTRAINT "chk_sler_criticality_nonneg" CHECK ("criticality" >= 0);
