import 'reflect-metadata';
import 'dotenv/config';
import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  ActivityType,
  AssessmentPurposeScope,
  ContainerStatus,
  ContentSource,
  LessonStatus,
  RevisionStatus,
} from '@prisma/client';
import { AppModule } from '../app.module';
import { PrismaService } from '../database/prisma.service';
import { AuthorizationRepository } from '../authorization/authorization.repository';
import { Argon2PasswordHasher, type PasswordHasher } from '../auth/password/password-hasher';
import { assertPasswordPolicy } from '../auth/password/password-policy';
import { bootstrapSystemRoles } from './system-roles';
import { DEMO_ADMIN } from './seed-demo';
import { PLACEMENT_ITEM_SCHEMA_VERSION } from '../assessment/scoring/item-payload';
import { PLACEMENT_CONFIG_SCHEMA_VERSION, PLACEMENT_ENGINE_VERSION } from '../assessment/engine/placement-engine.types';

/**
 * DEV/staging RUNTIME fixture (Phase 02B follow-up). `npm run db:seed:runtime`. NON-production, OPT-IN, idempotent.
 *
 * Purpose: publish the minimal-but-real content needed to drive the ACTUAL browser learner flow end to end against
 * izlan_dev — onboarding → placement → skill profile → initial roadmap → daily plan — which the demo seed cannot do
 * (its only subject is DRAFT, and there is no placement definition or eligible learning content).
 *
 * Design notes:
 *  - This is DATA SETUP only. It writes PUBLISHED content DIRECTLY via Prisma, exactly as the canonical
 *    placement/roadmap e2e fixtures do (test/placement-assessment.e2e-spec.ts, test/roadmap.e2e-spec.ts). It does
 *    NOT weaken any publication/lifecycle rule, and it does NOT bypass placement/roadmap validation: the placement
 *    engine still validates the pool/config at start, the skill profile is still derived from real submitted
 *    responses, and the initial roadmap is still generated by the real endpoint from the real diagnostic. The seed
 *    never creates an attempt, a skill snapshot, or a roadmap.
 *  - It leaves the normal demo seed UNTOUCHED: the demo `english-demo` subject stays DRAFT, and the demo learner
 *    (+998900000003) stays deliberately INCOMPLETE so onboarding-from-scratch QA still works. A SEPARATE runtime
 *    learner (+998900000004) is created pre-onboarded for fast placement/roadmap QA (Option A).
 *  - It does NOT auto-seed on application startup and is forbidden in production.
 */

/** Reuse the existing demo ADMIN as the content author (createdBy). No new staff account is invented. */
const RUNTIME_CREATOR = DEMO_ADMIN;
/** A dedicated, pre-onboarded learner for the post-onboarding flow — keeps the demo learner pristine for onboarding QA. */
export const RUNTIME_LEARNER = { phone: '+998900000004', displayName: 'Izlan Runtime Learner', roleCode: 'LEARNER' } as const;
// Learner-VISIBLE titles/descriptions are neutral & polished (no dev-grade labels in the investor journey). The SLUGS
// stay internal (never rendered) so existing contracts/tests that key on them are unaffected.
export const RUNTIME_SUBJECT = { slug: 'english-a1-dev', title: 'English — Beginner (A1)' } as const;
export const RUNTIME_SUBJECT_DESCRIPTION = 'Beginner English (A1): greetings, the verb “to be”, and subject pronouns.';
export const RUNTIME_TRACK = { slug: 'general-a1-dev', title: 'General English A1' } as const;

/** Stable skill codes (subject-scoped) — reused by both the lessons and the placement item pool. */
const SKILLS = [
  { code: 'ENG-A1-DEV-GREETINGS', name: 'Greetings & introductions', sortOrder: 1 },
  { code: 'ENG-A1-DEV-BE', name: 'The verb “to be”', sortOrder: 2 },
  { code: 'ENG-A1-DEV-PRONOUNS', name: 'Subject pronouns', sortOrder: 3 },
] as const;

export interface RuntimeFixtureEnv {
  nodeEnv: string | undefined;
  allowDevFixture: string | undefined;
  adminPassword: string | undefined;
  learnerPassword: string | undefined;
}

/** Fail closed: forbidden in production, requires ALLOW_DEV_FIXTURE=true and the (reused) demo passwords (policy-valid). */
export function assertRuntimeFixtureAllowed(env: RuntimeFixtureEnv): { adminPassword: string; learnerPassword: string } {
  if ((env.nodeEnv ?? '').trim() === 'production') throw new Error('db:seed:runtime is forbidden in production');
  if ((env.allowDevFixture ?? '').trim() !== 'true') throw new Error('db:seed:runtime requires ALLOW_DEV_FIXTURE=true');
  if (!env.adminPassword || !env.learnerPassword) {
    throw new Error('DEMO_ADMIN_PASSWORD and DEMO_LEARNER_PASSWORD are required');
  }
  assertPasswordPolicy(env.adminPassword);
  assertPasswordPolicy(env.learnerPassword);
  return { adminPassword: env.adminPassword, learnerPassword: env.learnerPassword };
}

interface Deps {
  prisma: PrismaService;
  authz: AuthorizationRepository;
  hasher: PasswordHasher;
}

/** Idempotent user ensure (same shape as the demo seed): user + profile + role + password credential. */
async function ensureUser(deps: Deps, def: { phone: string; displayName: string; roleCode: string }, password: string): Promise<string> {
  const { prisma, hasher } = deps;
  const existing = await prisma.user.findUnique({ where: { phone: def.phone } });
  const user = existing ?? (await prisma.user.create({ data: { phone: def.phone } }));
  await prisma.userProfile.upsert({ where: { userId: user.id }, create: { userId: user.id, displayName: def.displayName }, update: { displayName: def.displayName } });
  const role = await prisma.role.findUnique({ where: { code: def.roleCode } });
  if (!role) throw new Error(`role ${def.roleCode} not bootstrapped`);
  await prisma.userRole.upsert({ where: { userId_roleId: { userId: user.id, roleId: role.id } }, create: { userId: user.id, roleId: role.id, grantedBy: null }, update: {} });
  const passwordHash = await hasher.hash(password);
  await prisma.passwordCredential.upsert({ where: { userId: user.id }, create: { userId: user.id, passwordHash }, update: { passwordHash } });
  return user.id;
}

/** Ensure the full PUBLISHED container chain Subject→Track→Level→Module→Topic (idempotent by natural unique keys). */
async function ensureContainerChain(prisma: PrismaService, createdBy: string): Promise<{ subjectId: string; trackId: string; topicId: string }> {
  const subject = await prisma.subject.upsert({
    where: { slug: RUNTIME_SUBJECT.slug },
    create: { slug: RUNTIME_SUBJECT.slug, title: RUNTIME_SUBJECT.title, description: RUNTIME_SUBJECT_DESCRIPTION, status: ContainerStatus.PUBLISHED, sortOrder: 10, createdBy },
    update: { title: RUNTIME_SUBJECT.title, description: RUNTIME_SUBJECT_DESCRIPTION, status: ContainerStatus.PUBLISHED }, // keep visible + refresh polished copy on rerun; never demote
  });
  const track = await prisma.track.upsert({
    where: { subjectId_slug: { subjectId: subject.id, slug: RUNTIME_TRACK.slug } },
    create: { subjectId: subject.id, slug: RUNTIME_TRACK.slug, title: RUNTIME_TRACK.title, status: ContainerStatus.PUBLISHED, sortOrder: 1, createdBy },
    update: { status: ContainerStatus.PUBLISHED },
  });
  const level = await prisma.level.upsert({
    where: { trackId_code: { trackId: track.id, code: 'A1' } },
    create: { trackId: track.id, code: 'A1', title: 'A1', status: ContainerStatus.PUBLISHED, sortOrder: 1, createdBy },
    update: { status: ContainerStatus.PUBLISHED },
  });
  const moduleRow = await prisma.module.upsert({
    where: { levelId_sortOrder: { levelId: level.id, sortOrder: 1 } },
    create: { levelId: level.id, title: 'A1 Foundations', status: ContainerStatus.PUBLISHED, sortOrder: 1, createdBy },
    update: { status: ContainerStatus.PUBLISHED },
  });
  const topic = await prisma.topic.upsert({
    where: { moduleId_sortOrder: { moduleId: moduleRow.id, sortOrder: 1 } },
    create: { moduleId: moduleRow.id, title: 'Introductions & the verb “to be”', status: ContainerStatus.PUBLISHED, sortOrder: 1, createdBy },
    update: { status: ContainerStatus.PUBLISHED },
  });
  return { subjectId: subject.id, trackId: track.id, topicId: topic.id };
}

/** Ensure the 3 ACTIVE skills; returns code→id. Idempotent by (subjectId, code). */
async function ensureSkills(prisma: PrismaService, subjectId: string): Promise<Map<string, string>> {
  const byCode = new Map<string, string>();
  for (const s of SKILLS) {
    const row = await prisma.skill.upsert({
      where: { subjectId_code: { subjectId, code: s.code } },
      create: { subjectId, code: s.code, name: s.name, sortOrder: s.sortOrder },
      update: { name: s.name },
    });
    byCode.set(s.code, row.id);
  }
  return byCode;
}

/**
 * Ensure a PUBLISHED, learner-visible lesson: Lesson(PUBLISHED) + LessonRevision(PUBLISHED) + publishedRevisionId
 * pointer + LessonSkill mapping + optional prerequisite + published learner Activities (Phase 04). Idempotent by the
 * globally-unique contentKey (lesson) and by an empty-revision check (activities).
 */
async function ensurePublishedLesson(
  prisma: PrismaService,
  args: { topicId: string; createdBy: string; contentKey: string; title: string; sortOrder: number; skillId: string; prerequisiteLessonId?: string },
): Promise<string> {
  const existing = await prisma.lesson.findUnique({ where: { contentKey: args.contentKey } });
  const lesson = existing ?? (await prisma.lesson.create({
    data: { topicId: args.topicId, contentKey: args.contentKey, slug: args.contentKey.toLowerCase(), sortOrder: args.sortOrder, status: LessonStatus.PUBLISHED, createdBy: args.createdBy },
  }));

  // Ensure a PUBLISHED revision v1 and wire the published pointer (pointer coherence: revision.lessonId === lesson.id).
  let revision = await prisma.lessonRevision.findUnique({ where: { lessonId_version: { lessonId: lesson.id, version: 1 } } });
  if (!revision) {
    revision = await prisma.lessonRevision.create({
      data: { lessonId: lesson.id, version: 1, title: args.title, status: RevisionStatus.PUBLISHED, createdBy: args.createdBy, publishedBy: args.createdBy, publishedAt: new Date() },
    });
  }
  await prisma.lesson.update({ where: { id: lesson.id }, data: { status: LessonStatus.PUBLISHED, publishedRevisionId: revision.id } });

  // Skill mapping (idempotent) + optional prerequisite edge (idempotent).
  await prisma.lessonSkill.upsert({ where: { lessonId_skillId: { lessonId: lesson.id, skillId: args.skillId } }, create: { lessonId: lesson.id, skillId: args.skillId }, update: {} });
  if (args.prerequisiteLessonId) {
    await prisma.lessonPrerequisite.upsert({
      where: { lessonId_prerequisiteLessonId: { lessonId: lesson.id, prerequisiteLessonId: args.prerequisiteLessonId } },
      create: { lessonId: lesson.id, prerequisiteLessonId: args.prerequisiteLessonId },
      update: {},
    });
  }
  await ensureLessonActivities(prisma, revision.id, args.createdBy, args.skillId);
  return lesson.id;
}

// ── lesson activity payloads (Phase 04): view-only markdown + objective questions. answerKey is SERVER-ONLY (the
// learner projection strips it); schemaVersions are the lesson-activity contracts (distinct from placement items). ──
const LESSON_MD_V = 'lesson-activity-markdown/v1';
const LESSON_OBJ_V = 'lesson-activity-objective/v1';
const mdPayload = (markdown: string) => ({ schemaVersion: LESSON_MD_V, markdown });
const objSingle = (prompt: string, options: { id: string; text: string }[], correctId: string) => ({ schemaVersion: LESSON_OBJ_V, format: 'single_choice', prompt, options, answerKey: { correctOptionIds: [correctId] } });
const objTf = (prompt: string, correct: boolean) => ({ schemaVersion: LESSON_OBJ_V, format: 'true_false', prompt, options: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }], answerKey: { correctOptionIds: [correct ? 't' : 'f'] } });
const objMulti = (prompt: string, options: { id: string; text: string }[], correctIds: string[]) => ({ schemaVersion: LESSON_OBJ_V, format: 'multiple_choice', prompt, options, answerKey: { correctOptionIds: correctIds } });

/**
 * Seed one view-only step + three objective questions on a lesson revision. All three objectives map to the lesson's
 * skill via ActivitySkill, so completing the lesson yields real evidence and answering all three incorrectly can
 * legitimately trigger a REPEATED_MISTAKE review signal (the review flow's real prerequisite). Idempotent: only seeds
 * when the revision has no activities yet, atomically.
 */
async function ensureLessonActivities(prisma: PrismaService, revisionId: string, createdBy: string, skillId: string): Promise<void> {
  void createdBy; // Activity has no createdBy column; provenance is carried by `source`.
  if ((await prisma.activity.count({ where: { lessonRevisionId: revisionId } })) > 0) return;
  const objectives = [
    objSingle('Which of these is an English greeting?', [{ id: 'a', text: 'Hello' }, { id: 'b', text: 'Table' }, { id: 'c', text: 'Apple' }], 'a'),
    objTf('“I am a student.” is a correct sentence.', true),
    objMulti('Select the subject pronouns.', [{ id: 'a', text: 'I' }, { id: 'b', text: 'she' }, { id: 'c', text: 'apple' }], ['a', 'b']),
  ];
  await prisma.$transaction(async (tx) => {
    await tx.activity.create({
      data: { lessonRevisionId: revisionId, type: ActivityType.EXPLANATION, position: 0, source: ContentSource.HUMAN, payload: mdPayload('## Welcome\n\nRead this short explanation, then answer the questions below. Greetings are how we say **hello** and begin a conversation.') as object },
    });
    let position = 1;
    for (const payload of objectives) {
      const activity = await tx.activity.create({
        data: { lessonRevisionId: revisionId, type: position === 3 ? ActivityType.PRACTICE : ActivityType.MINI_QUESTION, position, source: ContentSource.HUMAN, payload: payload as object },
      });
      await tx.activitySkill.create({ data: { activityId: activity.id, skillId } });
      position++;
    }
  });
}

// ── placement item payloads (server-only answerKey; supported objective formats only) ──
const ITEM_V = PLACEMENT_ITEM_SCHEMA_VERSION;
const sc = (prompt: string, options: { id: string; text: string }[], correctId: string) => ({ schemaVersion: ITEM_V, format: 'single_choice', prompt, options, answerKey: { correctOptionIds: [correctId] } });
const tf = (prompt: string, correct: boolean) => ({ schemaVersion: ITEM_V, format: 'true_false', prompt, options: [{ id: 't', text: 'True' }, { id: 'f', text: 'False' }], answerKey: { correctOptionIds: [correct ? 't' : 'f'] } });
const mc = (prompt: string, options: { id: string; text: string }[], correctIds: string[]) => ({ schemaVersion: ITEM_V, format: 'multiple_choice', prompt, options, answerKey: { correctOptionIds: correctIds } });

/** Two items per skill (all 3 formats exercised), difficulties inside profileScale [1,6]. */
function placementItems(skills: Map<string, string>): { skillId: string; difficulty: number; payload: object }[] {
  const g = skills.get('ENG-A1-DEV-GREETINGS')!;
  const b = skills.get('ENG-A1-DEV-BE')!;
  const p = skills.get('ENG-A1-DEV-PRONOUNS')!;
  return [
    { skillId: g, difficulty: 2, payload: sc('Which is a polite morning greeting?', [{ id: 'a', text: 'Good morning' }, { id: 'b', text: 'Good night' }, { id: 'c', text: 'Goodbye' }], 'a') },
    { skillId: g, difficulty: 3, payload: tf('“Hello” is a way to greet someone.', true) },
    { skillId: b, difficulty: 3, payload: sc('She ___ a teacher.', [{ id: 'a', text: 'is' }, { id: 'b', text: 'are' }, { id: 'c', text: 'am' }], 'a') },
    { skillId: b, difficulty: 4, payload: mc('Select the correct forms of the verb “to be”.', [{ id: 'a', text: 'am' }, { id: 'b', text: 'is' }, { id: 'c', text: 'are' }, { id: 'd', text: 'bes' }], ['a', 'b', 'c']) },
    { skillId: p, difficulty: 2, payload: sc('___ am a student.', [{ id: 'a', text: 'I' }, { id: 'b', text: 'He' }, { id: 'c', text: 'They' }], 'a') },
    { skillId: p, difficulty: 3, payload: tf('“They” is a subject pronoun.', true) },
  ];
}

/**
 * Ensure the one PUBLISHED DIAGNOSTIC AssessmentDefinition for the subject + its PUBLISHED v1 + item pool.
 * Idempotent: reuse the existing PUBLISHED DIAGNOSTIC (a second one is DB-rejected); seed items only when the pool is empty.
 */
async function ensurePlacementDefinition(prisma: PrismaService, subjectId: string, createdBy: string, skills: Map<string, string>): Promise<{ definitionId: string; versionId: string; poolSize: number }> {
  const existingDef = await prisma.assessmentDefinition.findFirst({ where: { subjectId, purposeScope: AssessmentPurposeScope.DIAGNOSTIC, status: ContainerStatus.PUBLISHED } });
  const definition = existingDef ?? (await prisma.assessmentDefinition.create({
    data: { subjectId, purposeScope: AssessmentPurposeScope.DIAGNOSTIC, title: 'English A1 Placement', status: ContainerStatus.PUBLISHED, createdBy },
  }));

  const config = {
    schemaVersion: PLACEMENT_CONFIG_SCHEMA_VERSION,
    engine: PLACEMENT_ENGINE_VERSION,
    selection: { startDifficulty: 3, stepUp: 1, stepDown: 1 },
    coverage: { itemsPerSkill: 2 },
    stopping: { maxItems: 10 },
    profileScale: { minDifficulty: 1, maxDifficulty: 6 },
  };

  let version = await prisma.assessmentDefinitionVersion.findUnique({ where: { definitionId_versionNo: { definitionId: definition.id, versionNo: 1 } } });
  if (!version) {
    version = await prisma.assessmentDefinitionVersion.create({
      data: { definitionId: definition.id, versionNo: 1, config: config as object, status: RevisionStatus.PUBLISHED, createdBy, publishedAt: new Date() },
    });
  }
  if (definition.currentVersionId !== version.id) {
    await prisma.assessmentDefinition.update({ where: { id: definition.id }, data: { currentVersionId: version.id } });
  }

  // Seed the pool only when empty (items have no natural key) — atomic, so the count is either 0 or the full set.
  const poolCount = await prisma.assessmentVersionItem.count({ where: { versionId: version.id } });
  if (poolCount === 0) {
    const items = placementItems(skills);
    await prisma.$transaction(async (tx) => {
      for (const it of items) {
        const item = await tx.assessmentItem.create({
          data: { definitionId: definition.id, type: ActivityType.MINI_QUESTION, payload: it.payload, skillId: it.skillId, difficulty: it.difficulty, status: RevisionStatus.PUBLISHED, source: ContentSource.HUMAN },
        });
        await tx.assessmentVersionItem.create({ data: { versionId: version!.id, itemId: item.id } });
      }
    });
  }
  const poolSize = await prisma.assessmentVersionItem.count({ where: { versionId: version.id } });
  return { definitionId: definition.id, versionId: version.id, poolSize };
}

export interface RuntimeFixtureResult {
  subjectId: string;
  trackId: string;
  topicId: string;
  lessonIds: string[];
  definitionId: string;
  versionId: string;
  poolSize: number;
  learnerId: string;
  learnerIntentId: string;
}

/** Idempotent runtime fixture. Safe to rerun: no duplicate subject/track/definition/version/pool/learner. */
export async function runRuntimeFixture(deps: Deps, env: RuntimeFixtureEnv): Promise<RuntimeFixtureResult> {
  const { adminPassword, learnerPassword } = assertRuntimeFixtureAllowed(env);
  const { prisma } = deps;
  await bootstrapSystemRoles(deps.authz);

  // Content author (reuse the demo ADMIN) + the dedicated pre-onboarded runtime learner.
  const creatorId = await ensureUser(deps, RUNTIME_CREATOR, adminPassword);
  const learnerId = await ensureUser(deps, RUNTIME_LEARNER, learnerPassword);

  // Published content chain + skills + lessons.
  const { subjectId, trackId, topicId } = await ensureContainerChain(prisma, creatorId);
  const skills = await ensureSkills(prisma, subjectId);
  const l1 = await ensurePublishedLesson(prisma, { topicId, createdBy: creatorId, contentKey: 'ENG-A1-DEV-L1', title: 'Saying hello', sortOrder: 1, skillId: skills.get('ENG-A1-DEV-GREETINGS')! });
  const l2 = await ensurePublishedLesson(prisma, { topicId, createdBy: creatorId, contentKey: 'ENG-A1-DEV-L2', title: 'The verb “to be”', sortOrder: 2, skillId: skills.get('ENG-A1-DEV-BE')!, prerequisiteLessonId: l1 });
  const l3 = await ensurePublishedLesson(prisma, { topicId, createdBy: creatorId, contentKey: 'ENG-A1-DEV-L3', title: 'Subject pronouns', sortOrder: 3, skillId: skills.get('ENG-A1-DEV-PRONOUNS')!, prerequisiteLessonId: l2 });

  // Published diagnostic placement definition + pool (validated by the real engine at start).
  const placement = await ensurePlacementDefinition(prisma, subjectId, creatorId, skills);

  // Pre-onboard the runtime learner (keeps the demo learner untouched) + a current learning intent for this subject/track.
  await prisma.userProfile.update({
    where: { userId: learnerId },
    data: { displayName: RUNTIME_LEARNER.displayName, dateOfBirth: new Date('2000-01-01'), timezone: 'Asia/Tashkent', onboardingCompletedAt: new Date() },
  });
  const intent = await prisma.learnerLearningIntent.upsert({
    where: { userId_subjectId: { userId: learnerId, subjectId } },
    create: { userId: learnerId, subjectId, trackId },
    update: { trackId },
  });

  return { subjectId, trackId, topicId, lessonIds: [l1, l2, l3], definitionId: placement.definitionId, versionId: placement.versionId, poolSize: placement.poolSize, learnerId, learnerIntentId: intent.id };
}

async function main(): Promise<void> {
  const logger = new Logger('SeedRuntime');
  const app = await NestFactory.createApplicationContext(AppModule, { logger: ['error', 'warn', 'log'] });
  try {
    const result = await runRuntimeFixture(
      { prisma: app.get(PrismaService), authz: app.get(AuthorizationRepository), hasher: new Argon2PasswordHasher() },
      { nodeEnv: process.env.NODE_ENV, allowDevFixture: process.env.ALLOW_DEV_FIXTURE, adminPassword: process.env.DEMO_ADMIN_PASSWORD, learnerPassword: process.env.DEMO_LEARNER_PASSWORD },
    );
    logger.log(`Runtime fixture ready — subject=${RUNTIME_SUBJECT.slug} (${result.subjectId}) track=${RUNTIME_TRACK.slug} lessons=${result.lessonIds.length} poolSize=${result.poolSize} runtimeLearner=${RUNTIME_LEARNER.phone} intent=${result.learnerIntentId}`);
    logger.log('Demo learner +998900000003 remains INCOMPLETE for onboarding-from-scratch QA. Demo english-demo subject remains DRAFT.');
  } finally {
    await app.close();
  }
}

// Only run as a CLI entrypoint, not when imported by tests.
if (require.main === module) {
  main().catch((err) => {
    new Logger('SeedRuntime').error(`Runtime fixture failed: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
